{% set name = "riboSeed" %}
{% set version = "0.4.41" %}
{% set hash_type = "sha256" %}
{% set hash_value = "2471aa10649997a7a6335dfc2516c6cdacd2c578d182de4718d44aebc2fb3d76" %}
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://test-files.pythonhosted.org/packages/b7/20/0cf9d39cf603d88b6a8f3209bee7b1a9aacbb9c1721166245c08d46ce6b9/riboSeed-0.4.41.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  entry_points:
    - ribo = riboSeed.ribo:main
  number: 1
  skip: True  # [win]
  skip: True  # [py2k]
  skip: True  # [py34]
requirements:
  build:
    - python
    - setuptools
    - biopython ==1.68
    - pysam ==0.11.2.2
    - jenkspy ==0.1.4
    - pyaml ==17.8.0
    - pyutilsnrw ==0.1.1
    - matplotlib ==1.5.3
    - pandas ==0.20.1
    - coverage ==4.4.1
    - nose ==1.3.7
  run:
    # python reqs
    - python
    - biopython ==1.68
    - jenkspy ==0.1.4
    - pyaml ==17.8.0
    - pysam ==0.11.2.2
    - pyutilsnrw ==0.1.1
    - matplotlib ==1.5.3
    - pandas ==0.20.1
    - coverage ==4.4.1
    - nose ==1.3.7
    # sys reqs
    - emboss
    - barrnap ==0.7
    - mafft
    - prank
    - spades ==3.9.0
    - bwa ==0.7.8
    - samtools ==1.4.1
    - bcftools ==1.5

test:
  imports:
    - riboSeed
  commands:
    - ribo
    - ribo run -h
    - ribo scan -h
    - ribo snag -h
    - ribo sketch -h
    - ribo stack -h
    - $PYTHON -m unittest tests.test_conda

about:
  home: https://github.com/nickp60/riboSeed
  license: MIT License
  license_family: MIT
  license_file: 'LICENSE'
  summary: 'riboSeed: assemble across rDNA regions'
  description: "Genome assembly polisher to bridge rDNA gaps"
  dev_url: 'https://github.com/nickp60/riboSeed'

extra:
  recipe-maintainers:
    - nickp60

