{% set name = "sis" %}
{% set version = "0.1.0" %}
{% set sha256 = "045be63ebea2592d823c024ee506219f5ad0e73a84b09416808db80ae9b0c160" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: sis.zip
  url: http://marte.ic.unicamp.br:8747/static/sis.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx] [py3]

requirements:
  build:

  run:
    - mummer

test:
  commands:
     - python2.7 sis.py

about:
  home: http://marte.ic.unicamp.br:8747/
  license: This software is experimental in nature and is supplied "AS IS", without obligation by the authors to provide  accompanying services or support.  The entire risk as to the quality  and performance of the Software is with you. The authors EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES REGARDING THE SOFTWARE,  WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES  PERTAINING TO MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
  summary: A tool that uses mummer to scaffold small genomes.
  maintainer: nickp60
