{% set version = '1.5.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vcfr
  version: {{ version|replace("-", "_") }}

source:
  fn: vcfR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/vcfR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/vcfR/vcfR_{{ version }}.tar.gz


  sha256: 7cd7d352d72120cf6127c9ef86b5134135d66bb4f047945c75aa0b99cc741a22
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: adegenet, ggplot2, knitr, poppr, reshape2, rmarkdown, scales, testthat
requirements:
  build:
    - r-base
    - r-rcpp
    - r-ape
    - r-dplyr
    - r-magrittr
    - r-memuse
    - r-pinfsc50
    - r-stringr
    - r-tidyr
    - r-vegan
    - r-viridislite
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp
    - r-ape
    - r-dplyr
    - r-magrittr
    - r-memuse
    - r-pinfsc50
    - r-stringr
    - r-tidyr
    - r-vegan
    - r-viridislite{indent}libgcc  # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('vcfR')"  # [not win]
    - "\"%R%\" -e \"library('vcfR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/knausb/vcfR, https://knausb.github.io/ vcfR_documentation/
  license: GPL
  summary: Facilitates easy manipulation of variant call format (VCF) data. Functions are provided
    to rapidly read from and write to VCF files. Once VCF data is read into R a parser
    function extracts matrices of data. This information can then be used for quality
    control or other purposes. Additional functions provide visualization of genomic
    data. Once processing is complete data may be written to a VCF file (*.vcf.gz).
    It also may be converted into other popular R objects (e.g., genlight, DNAbin).
    VcfR provides a link between VCF data and familiar R software.
  license_family: GPL

# The original CRAN metadata for this package was:

# Package: vcfR
# Title: Manipulate and Visualize VCF Data
# Description: Facilitates easy manipulation of variant call format (VCF) data. Functions are provided to rapidly read from and write to VCF files. Once VCF data is read into R a parser function extracts matrices of data. This information can then be used for quality control or other purposes. Additional functions provide visualization of genomic data. Once processing is complete data may be written to a VCF file (*.vcf.gz). It also may be converted into other popular R objects (e.g., genlight, DNAbin). VcfR provides a link between VCF data and familiar R software.
# Version: 1.5.0
# Authors@R: c(person(c("Brian", "J."), "Knaus", role = c("cre", "aut"), email = "briank.lists@gmail.com"), person(c("Niklaus", "J."), "Grunwald", role = "aut", email = "grunwaln@science.oregonstate.edu"), person(c("Eric", "C."), "Anderson", role = "ctb", email = "eric.anderson@noaa.gov"), person(c("David", "J."), "Winter", role = "ctb", email = "david.winter@gmail.com"), person(c("Zhian", "N."), "Kamvar", role = "ctb", email = "zkamvar@gmail.com"))
# Maintainer: Brian J. Knaus <briank.lists@gmail.com>
# URL: https://github.com/knausb/vcfR, https://knausb.github.io/ vcfR_documentation/
# Depends: R (>= 3.0.1)
# LinkingTo: Rcpp
# Imports: ape, dplyr, graphics, grDevices, magrittr, memuse, methods, pinfsc50, Rcpp, stats, stringr, tidyr, utils, vegan, viridisLite
# Suggests: adegenet, ggplot2, knitr, poppr, reshape2, rmarkdown, scales, testthat
# VignetteBuilder: knitr
# License: GPL
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-05-17 20:40:08 UTC; knausb
# Author: Brian J. Knaus [cre, aut], Niklaus J. Grunwald [aut], Eric C. Anderson [ctb], David J. Winter [ctb], Zhian N. Kamvar [ctb]
# Repository: CRAN
# Date/Publication: 2017-05-18 04:17:39 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
